server:
  port: 8885  # 指定该实例的端口
  servlet:
    application-display-name: wordfilter
    context-path: /wd

spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false






